CREATE SEQUENCE if not exists SEQ_PLAYBILL;

CREATE TABLE if not exists PLAYBILL
(
    ID           INT NOT NULL,
    NAME         VARCHAR (255) NOT NULL,
    DESCRIPTION  VARCHAR (2000),
    AGE_CATEGORY VARCHAR (30),
    SEATS        INT NOT NULL,
    SEATS_SOLD   INT DEFAULT 0 NOT NULL,
    CONSTRAINT PLAYBILL_PK PRIMARY KEY (ID),
    CONSTRAINT PLAYBILL_UQ UNIQUE (NAME)
);